---
title: "Alaska salmo data"
format: html
editor: visual
---

```{r}
library(dplyr)
library(tidyr)
library(readr)
```

## Data Sources

-   Read data

```{r}
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")

```

-   Explore data

    ```{r}

    ## Prints the column names of my data frame
    colnames(catch_original)

    ## First 6 lines of the data frame
    head(catch_original)

    ## Summary of each column of data
    summary(catch_original)

    ## Prints unique values in a column (in this case, the region)
    unique(catch_original$Region)

    ## Opens data frame in its own tab to see each row and column of the data (do in console)
    View(catch_original)
    ```

```{r}
catch_data <- catch_original %>%
    select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)

head(catch_data)
```

```{r}

```

```{r}
catch_data <- catch_original %>% 
    select(-All,-notesRegCode)

head(catch_data)
```

-   Quality check

```{r}
dplyr::glimpse(catch_data)
```

```{r}
catch_clean <- catch_data %>%
    mutate(Chinook = as.numeric(Chinook))
head(catch_clean)
```

```{r}
i <- which(is.na(catch_clean$Chinook))
i
```

```{r}
catch_clean <- catch_data %>% mutate(Chinook = if_else(condition = Chinook == "I", true = "1", false = Chinook), Chinook = as.numeric(Chinook))

##check catch_clean[i, ]
```

-   changing shape

    ```{r}
    catch_long <- catch_clean %>% 
        #pivot longer all columns except Region and Year
        pivot_longer(
            cols = -c(Region, Year),
            names_to = "species",
            values_to = "catch"
        )

    head(catch_long)
    ```

```{r}
catch_wide <- catch_long %>%
    pivot_wider(names_from = species,
                values_from = catch)

head(catch_wide)
```

-   Renaming columns

```{r}
catch_long <- catch_long %>%
    rename(catch_thousands = catch)

head(catch_long)
```

```{r}
catch_long <- catch_long %>%
    mutate(catch = catch_thousands * 1000)

head(catch_long)
```

### Summary statistics

```{r}
unique(catch_original$Region)
```

```{r}
mean_region <- catch_long %>%
    group_by(Region) %>%
    summarize(mean_catch = mean(catch))

head(mean_region)
```

```{r}
n_region <- catch_long %>%
    group_by(Region) %>%
    summarize(n = n())

head(n_region)

```

```{r}
catch_year_sp <- catch_long %>%
    group_by(Year, species) %>%
    summarize(total_year = sum(catch, na.rm = T))
```

-filter data

```{r}
sse_catch <- catch_long %>% filter(Region == "SSE")

head(sse_catch)
```

```{r}
## Catches over a million fish
catch_million <- catch_long %>%
    filter(catch > 1000000)

## Chinook from SSE data
chinook_see <- catch_long %>%
    filter(Region == "SSE",
           species == "Chinook")

## OR
chinook_see <- catch_long %>%
    filter(Region == "SSE" & species == "Chinook")
```

-sorting data

```{r}
mean_region <- catch_long %>%
    group_by(Region) %>%
    summarize(mean_catch = mean(catch)) %>%
    arrange(mean_catch)

head(mean_region)

```

```{r}
mean_region <- catch_long %>%
    group_by(Region) %>%
    summarize(mean_catch = mean(catch)) %>%
    arrange(desc(mean_catch))

head(mean_region)
```

-   Splitting a column

    ```{r}
    sites_df <- data.frame(site = c("HAW-101",
                                    "HAW-103",
                                    "OAH-320",
                                    "OAH-219",
                                    "MAU-039"))

    sites_df %>%
        separate(site, c("island", "site_number"), "-")
    ```

```{r}
## create `cities_df`
cities_df <- data.frame(city = c("Juneau AK",
                                 "Sitka AK",
                                 "Anchorage AK"))

colnames(cities_df)

cities_clean <- cities_df %>%
    separate(city, c("city", "state_code"), " ")
head(cities_clean)
```

```{r}
dates_df <- data.frame(
    year = c("1930",
             "1930",
             "1930"),
    month = c("12",
              "12",
              "12"),
    day = c("14",
            "15",
            "16")
)

dates_df %>%
    unite(date, year, month, day, sep = "-")
```

```{r}
catch_original <- read_csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", 
                               method = "libcurl"))

mean_region <- catch_original %>%
  select(-All, -notesRegCode) %>% 
  mutate(Chinook = ifelse(Chinook == "I", 1, Chinook)) %>% 
  mutate(Chinook = as.numeric(Chinook)) %>% 
  pivot_longer(-c(Region, Year), 
               names_to = "species", 
               values_to = "catch") %>%
  mutate(catch = catch*1000) %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch)) %>% 
  arrange(desc(mean_catch))

head(mean_region)
```
