---
title: "shp_proc"
format: html
editor: visual
---

```{r}
library(readr)
library(sf)
library(ggplot2)
library(leaflet)
library(scales)
library(ggspatial)
library(dplyr)
library(tidyverse)
library(stringi)
```

```{r}
reg <- read_sf("data/32p.shp")
nrow(reg)
head(reg)
```

```{r}


```

```{r}
species_name <- function(df, species){
    return_df <- left_join(df, species, by = c("species" = "alpha_code"))
    return(return_df)
}
```

```{r}
reg2 <- filter(reg, TYPE_TER =='TRF')
nrow(reg)
nrow(reg2)


```

```{r}
reg3 <- reg2 %>% ?(GR_ESS = ifelse(is.na(GR_ESS), 0, GR_ESS))
head(reg3)

```

```{r}
sp_data <- reg3 %>% select(GR_ESS)
head(sp_data)
```

```{r}
#ttt <- str_extract(sp_data, "EN")
#head(ttt)

#ttt  %>% filter(spec %in% sp_data)

 # mutate(
 #   s22 = SUPERFICIE*2 ) 
```

```{r}

vec <- c(2,2,2,2, 2,2,2,2)

names(vec) <- c("EN", "EB", "PG", "SB", "ML", "BP", "BJ","PT")

#sp_data <- reg3 %>% select(GR_ESS)

ttt <- tibble (sp_data)|> separate_wider_position(GR_ESS, widths = vec, too_few = 'align_start')

ttt



```
